---

# - name: Check if InfluxData repository exist
#   stat:
#     path: /etc/apt/sources.list.d/influxdb.list
#   register: influxdata_repository

- name: Install apt-transport-https (Debian)
  apt:
    name: apt-transport-https
    state: present
  when:  ansible_distribution == "Debian"
    # ansible_distribution == "Debian" and influxdata_repository.stat.exists != True

- name: Add the InfluxData repository key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  # when: influxdata_repository.stat.exists != True

- name: Add InfluxData repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    filename: "influxdb"
    state: present
  # when: influxdata_repository.stat.exists != True
  register: repository_influxdb

- name: Install the influxdb
  apt:
    name: influxdb
    update_cache: yes
  when: repository_influxdb.changed

- name: Start influxdb
  service:
    name: influxdb
    state: restarted
    enabled: yes

- name: Influxdb - Create user admin
  command: /opt/influxdb/influx -execute "CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES"

- name: Influxdb - Show users
  command: /opt/influxdb/influx -execute "SHOW USERS"

- name: Influxdb - Create telegraf db
  command: /opt/influxdb/influx -execute "CREATE DATABASE {{ influxdb_db }}"

- name: Influxdb - Show databases
  command: /opt/influxdb/influx -execute "SHOW DATABASES"

- name: Influxdb - Create telegraf user
  command: /opt/influxdb/influx -execute "CREATE USER {{ influxdb_user }} WITH PASSWORD {{ influxdb_password }} WITH ALL PRIVILEGES"

- name: Influxdb - Show users (2)
  command: /opt/influxdb/influx -execute "SHOW USERS"

- name: Influxdb - Grant privileges on telegraf db to telegraf user
  command: /opt/influxdb/influx -execute "GRANT ALL PRIVILEGES ON {{ influxdb_db }} TO {{ influxdb_user }}"
