---

- hosts: management_services_host
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/influxdb
    - role: management_configuration/grafana
    - role: management_configuration/createtelegrafdb

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/telegraf

- hosts: k3s_master
  become: yes
  roles:
    - role: management_configuration/getkubeconfig

- hosts: manager_machine
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/kubectl