---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s_configuration/prereq
    - role: k3s_configuration/download
    - role: k3s_configuration/raspberrypi
    - role: management_configuration/telegraf

- hosts: k3s_master
  become: yes
  roles:
    - role: k3s_configuration/k3s/master

- hosts: k3s_node
  become: yes
  roles:
    - role: k3s_configuration/k3s/node

- hosts: management_services_host
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/influxdb
    # - role: management_configuration/grafana # on host

- hosts: manager_machine
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/kubectl
    - role: management_configuration/grafana # on k3s
    - role: management_configuration/webui # on k3s
