---

- hosts: k3s_master
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/influxdb
    - role: management_configuration/kubeconfig

- hosts: manager_machine
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/kubectl
    - role: management_configuration/grafana # on k3s

- hosts: k3s_master
  become: yes
  roles:
    - role: management_configuration/telegrafdb
