---

- hosts: management_services_host
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_influxdb

- hosts: manager_machine
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_kubectl
