---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s_configuration/reset
    - role: management_configuration/reset_telegraf

- hosts: management_services_host
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_influxdb

- hosts: management_interface_host
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_kubectl
