---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_telegraf

- hosts: manager_machine
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_kubectl

- hosts: management_services_host
  gather_facts: yes
  become: yes
  roles:
    - role: management_configuration/reset_grafana
    - role: management_configuration/reset_influxdb
