---

- name: Create user admin on influxdb
  command: influx -execute "CREATE USER {{ influxdb_admin_user }} WITH PASSWORD '{{ influxdb_admin_password }}' WITH ALL PRIVILEGES"

- name: Influxdb - Create telegraf db
  command: influx -execute "CREATE DATABASE {{ influxdb_db }}"

- name: Show databases
  command: influx -execute "SHOW DATABASES"
  register: output

- name: Print databases
  debug:
    var: output

- name: Create telegraf user on influxdb
  command: influx -execute "CREATE USER {{ influxdb_user }} WITH PASSWORD '{{ influxdb_password }}' WITH ALL PRIVILEGES"

- name: Show db users
  command: influx -execute "SHOW USERS"
  register: output

- name: Print db users
  debug:
    var: output

- name: Grant privileges on telegraf db to telegraf user
  command: influx -execute "GRANT ALL PRIVILEGES ON {{ influxdb_db }} TO {{ influxdb_user }}"
