---
- name: Remove Telegraf
  apt:
    name: telegraf
    state: absent

- name: Remove InfluxData repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    filename: "influxdb"
    state: absent

- name: Remove the InfluxData repository key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: absent

- name: Remove apt-transport-https
  apt:
    name: apt-transport-https
    state: absent
  when: ansible_distribution == "Debian"