---

- name: Remove influxdb
  apt:
    name: influxdb
    state: absent

- name: Remove InfluxData repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    filename: "influxdb"
    state: absent

- name: Remove the InfluxData repository key
  apt_key:
    id: 05CE15085FC09D18E99EFB22684A14CF2582E0C5
    state: absent

- name: Remove apt-transport-https
  apt:
    name: apt-transport-https
    state: absent
  when: ansible_distribution == "Debian"
