# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: grafana-pv
#   labels:
#     app: grafana
# spec:
#   storageClassName: local-path
#   persistentVolumeReclaimPolicy: Retain
#   capacity:
#     storage: 200Mi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /tmp/k3s-volumes/grafana
#     type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  # volumeName: grafana-pv
  resources:
    requests:
      storage: 200Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.3.7
        ports:
        - name: grafana-port
          containerPort: 3000
        volumeMounts:
        - name: grafana-volume
          mountPath: /var/lib/grafana
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1001
      #   fsGroup: 1001
      #   fsGroupChangePolicy: "OnRootMismatch"
      # nodeSelector:
      #   worker: allocator

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      nodePort: 30000
      targetPort: grafana-port
      protocol: TCP
  selector:
    app: grafana
  type: NodePort
